name: "S3 Upload"
description: "Uploads a file to S3 and invalidate CouldFront distribution."
author: "Jacob Arvidsson"
branding:
  icon: "check-square"
  color: "green"
inputs:
  FILE:
    description: "Source of file to upload"
    default: ""
  DEST:
    description: "Destination in the bucket"
    default: ""
  AWS_S3_BUCKET:
    description: "Bucket to upload to"
    default: ""
  AWS_SECRET_KEY:
    description: "AWS Secret Key"
    default: ""
  AWS_SECRET_ID:
    description: "AWS Secret Key"
    default: ""
  AWS_REGION:
    description: "AWS Region"
    default: ""
  AWS_DISTRIBUTION_ID:
    description: "Distribution id to invalidate CloudFront"
    default: ""
runs:
  using: "node12"
  main: "index.js"
